
jQuery(document).ready(function($){var autoLogoutTimeout=30*60000;var heartbeatInterval=60000;var idleTimeout=60;var idleTimer=0;var userInputTime=new Date().getTime();if(typeof appContext!="undefined"){jQuery(this).bind("mousemove keypress",function(){resetAutoLogoutTimer();});window.setInterval(function(){var elapsed=Math.floor((new Date().getTime()-userInputTime)/100)/10;if(elapsed<idleTimeout){jQuery.post("/myjmh-client/tiles/heartbeat",{currentPageAction:appContext.currentPageAction,relatedSubjectName:appContext.relatedSubjectName,currentSubjectRelId:appContext.currentSubjectRelId,relatedSubjectId:appContext.relatedSubjectId,relatedSubjectIdType:appContext.relatedSubjectIdType,currentMode:appContext.currentMode,rootMode:appContext.rootMode});}},heartbeatInterval);}
function resetAutoLogoutTimer(){window.clearTimeout(idleTimer);userInputTime=new Date().getTime();idleTimer=window.setTimeout(logoutUser,autoLogoutTimeout);}
function logoutUser(){document.body.innerHTML="";window.location="/myjmh-client/logout";}
jQuery("div.title").first().find("h1").hide();jQuery("div.title").first().addClass("hide-first-title");jQuery("#main").show();jQuery("#assistiveicons a").each(function(a){if(jQuery(this).attr("id")==="printerfriendlylink"){jQuery(this).append(" Print");}else{var img=jQuery(this).find("img")[0];var aTitle=jQuery(img).attr("title");var assistTitle=assistTextMap[aTitle];if((typeof assistTitle==='undefined')||assistTitle==null){assistTitle=aTitle;}
jQuery(this).append(" <div style='display:inline'>"+assistTitle+"</div>");}});jQuery("#assistiveicons").appendTo("#viewing-info-div");jQuery("#assistiveicons").show();jQuery("div.actionmenucontainer ul.actionmenu li.actionmenuitem a div").each(function(){jQuery(this).remove();});jQuery(".section.search .content").eq(1).find("p").css("margin","12px 0");jQuery(".section.search .content").eq(1).find("br").remove();jQuery(window).resize(function(){jQuery('#blotter').css('width','auto');if($(window).width()<954){$('.fixer').css('padding','0 20px');}});$(":input[data-watermark]").each(function(){if($(this).val()==''){$(this).val($(this).attr("data-watermark"));$(this).css('color','#a8a8a8');}
$(this).bind('focus',function(){if($(this).val()==$(this).attr("data-watermark"))$(this).val('');$(this).css('color','');});$(this).bind('blur',function(){if($(this).val()==''){$(this).val($(this).attr("data-watermark"));$(this).css('color','#a8a8a8');}});});jQuery(".uploader iframe.fileselector").css('width','90px');jQuery(".uploader iframe.fileselector").css('height','40px');jQuery(".inside1 .hide-first-title h1").css("display","block");jQuery(".inside1 .hide-first-title").each(function(){jQuery(this).removeClass("hide-first-title");});jQuery(".inside1 span.right.h3").css("margin-top","10px");jQuery("#currentoutstandingaccts p.noprint a").each(function(){if(jQuery(this).attr("href").indexOf("inside1.asp?mode=sbostatementdetail")!=-1){jQuery(this).addClass("outstanding_accounts_link");jQuery(this).removeAttr("onclick");jQuery(this).removeAttr("target");}});jQuery("#currentoutstandingaccts").each(function(){createPostForm("outstanding_accounts_popup");});jQuery(".outstanding_accounts_link").on("click",function(){var action=jQuery(this).attr("href");var popup=jQuery("#outstanding_accounts_popup");popup.attr('action',action);popup.submit(function(e){window.open('','popup','width=1024,resizable,status,scrollbars').focus();this.target='popup';});popup.submit();return false;});jQuery("table[id^=statementdetails]").each(function(){createPostForm("statement_details_popup");});jQuery("[id^=statementdetails] tbody tr").each(function(){jQuery(this).css("cursor","pointer");var a=jQuery(this).find("td a")[0];if(typeof a!=="undefined"){var href=jQuery(a).attr("href");jQuery(this).removeAttr("onclick");jQuery(this).data("link",href);}});jQuery("[id^=statementdetails] tbody tr").on("click",function(){var action=jQuery(this).data("link");var parameters;var splitIndex=action.indexOf('?');var popup=jQuery("#statement_details_popup");popup.attr('action',action);if(splitIndex>0){parameters=action.substring(splitIndex+1);jQuery('#statement_details_popupparameters').attr('value',parameters);}
popup.submit();return false;});jQuery("#printerfriendlylink").each(function(){if(jQuery(this).attr("href").indexOf("printmode=true")!=-1){jQuery(this).removeAttr("onclick");jQuery(this).removeAttr("target");jQuery(this).data("link",jQuery(this).attr("href"));jQuery(this).removeAttr("href");createPostForm("printForm");}});jQuery("#printerfriendlylink").on("click",function(e){e.preventDefault();var action=jQuery(this).data("link");if(action.indexOf("rootMode=growthchart&originalMethod=get&")!=-1){action=action.replace("rootMode=growthchart&originalMethod=get&",'');}
jQuery('#printForm').attr('action',action);jQuery('#printForm').submit(function(e){window.open('','pw','width=800,height=600,resizable,status,scrollbars').focus();this.target='pw';});jQuery("#printForm").submit();return false;});jQuery("#personalForm div#notifprefs .content p a").addClass("anchorNode");function createPostForm(id){jQuery("body").append("<form id=\""+id+"\" method=\"POST\" action=\"\">"
+"<input id=\""+id+"RootMode\" type=\"hidden\" name=\"rootMode\" value=\"\" />"
+"<input id=\""+id+"changeContextSubjectRelId\" type=\"hidden\" name=\"subjectRelId\" value=\"\" />"
+"<input id=\""+id+"changeContextRelSubjectId\" type=\"hidden\" name=\"relatedSubjectId\" value=\"\" />"
+"<input id=\""+id+"changeContextRelSubjectIdType\" type=\"hidden\" name=\"relatedSubjectIdType\" value=\"\" /> "
+"<input id=\""+id+"parameters\" type=\"hidden\" name=\"parameters\" value=\"\" /> "
+"</form>");jQuery('#'+id+'RootMode').attr('value',appContext.rootMode);jQuery('#'+id+'changeContextSubjectRelId').attr('value',appContext.currentSubjectRelId);jQuery('#'+id+'changeContextRelSubjectId').attr('value',appContext.relatedSubjectId);jQuery('#'+id+'changeContextRelSubjectIdType').attr('value',appContext.relatedSubjectIdType);}
jQuery("form#timeselection").each(function(){if(jQuery("form#timeselection").attr("action").indexOf("inside.asp?mode=recentpay")!=-1){jQuery("form#timeselection").attr("action","inside.asp?mode=recentpay&ref=as");jQuery("#printerfriendlylink").data("link","inside.asp?mode=recentpay&ref=as&eid=1&type=3&printmode=true");}});var patInfoPretextHtml="<span id='myjmh-override-1'>If any information below is incorrect or incomplete, please <a href='inside.asp?mode=demog'>update your profile</a>.</span>";jQuery("div#datatile p a[href='inside.asp?mode=custsvc&from=patinfo']").parent().html(patInfoPretextHtml);(function(){if(typeof document.getElementById("mainForm")!="undefined"&&document.getElementById("mainForm")!=null){var growthChartFormSubmit=document.getElementById("mainForm").submit;document.getElementById("mainForm").submit=function(){processInsideAspRequest(this);growthChartFormSubmit.apply(this);return false;};}})();jQuery("a[href$='dashboard']").on("click",function(){jQuery('#changeContext').attr('action',dashboardAction);jQuery('#changeContextSubjectRelId').attr('value',appContext.currentSubjectRelId);jQuery('#changeContextMode').attr('value','');jQuery('#changeContextRelSubjectId').attr('value',appContext.relatedSubjectId);jQuery('#changeContextRelSubjectIdType').attr('value',appContext.relatedSubjectIdType);jQuery('#changeContext').submit();return false;});jQuery("#proxyprefform table tr").on("click",function(e){var thisRowsName=jQuery(this).find("td:nth-child(2)")[0].innerHTML;jQuery("#viewing-info-div ul.dropdown-menu li").each(function(index,li){var nameFromProxySelect=li.innerText;var jsFunction=jQuery(jQuery(li).find("a")[0]).attr("href").split(":")[1].replace("pickSubject","pickSubjectDashboard");if(thisRowsName.indexOf(nameFromProxySelect)!=-1){eval(jsFunction);return false;}});return false;});if(!(typeof appContext=='undefined')&&!(typeof appContext.modeUrl=='undefined')&&appContext.modeUrl!=""){jQuery("form#sendvisit").attr('action',appContext.modeUrl);}
jQuery("form[action*='inside.asp']").on("submit",function(event){processInsideAspRequest(this);});var messagesPerPageInboxForm=document.getElementById("msglist_inbox_lstSzForm");if(messagesPerPageInboxForm){var messagesPerPageInboxFormSubmit=messagesPerPageInboxForm.submit;messagesPerPageInboxForm.submit=function(){processInsideAspRequest(this);messagesPerPageInboxFormSubmit.apply(this);return false;};}
var resultsPerPageLabsForm=document.getElementById("RESULTS_results_lstSzForm");if(resultsPerPageLabsForm){var resultsPerPageLabsFormSubmit=resultsPerPageLabsForm.submit;resultsPerPageLabsForm.submit=function(){processInsideAspRequest(this);resultsPerPageLabsFormSubmit.apply(this);return false;};}
jQuery("div#claimslist table tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});jQuery("div#appts table tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});jQuery("div#hospitalizations table tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});jQuery("div#apptlistsec table tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});jQuery("#msglist_inbox_tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});jQuery("#RESULTS_results_tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});if(!(typeof appContext=='undefined')&&appContext.currentMode=="sendvisit"){if(jQuery("form#sendvisit").length>0){jQuery("div#datatile div#search p").first().html("Enter your doctors information to start your search.");var postHref=jQuery("div#datatile div#search p:last-child a").attr("href");var newPostStr="If you have your doctors address you may <a href=\""+postHref+"\">manually enter</a> it.";jQuery("div#datatile div#search p:last-child").html(newPostStr);}else if(jQuery("form#directaddress").length>0){jQuery("div#datatile div#direct p").first().html("Enter the address provided by your physician.");}}
jQuery("div#questionnaires table tbody tr[onclick*='window.location.href']").each(function(index,tr){processTableRowClick(index,tr);});jQuery("div#questionnaires table tbody td  a[onclick*='src=appt&printmode=true']").each(function(index,elem){handleQuestionnairePrint(index,elem)});jQuery("div#relatedquestionnaires table tbody td  a[onclick*='mode=histques&requestsent=true&printmode=true']").each(function(index,elem){handleQuestionnairePrint(index,elem)});jQuery("input[onclick*='mode=histques&src=appt']").each(function(index,elem){var clickUrlStr=jQuery(elem).attr("onclick");var urlMatch=(/self.location.href='(.*)'/g).exec(clickUrlStr);var clickUrl=urlMatch[1];jQuery(elem).data("link",clickUrl);jQuery(elem).removeAttr("onclick");jQuery(elem).click(function(event){var cUrl=jQuery(this).data("link");return gotoInsideAsp(cUrl,"",event);});});function processTableRowClick(index,tr){var rx=/window.location.href='(.*)'/g;var trOnclick=jQuery(tr).attr("onclick");var hrefValue=rx.exec(trOnclick);jQuery(tr).attr("onclick","gotoInsideAsp('"+hrefValue[1]+"')");}
var makeEditButtons=jQuery("input#makeedits");makeEditButtons.each(function(index,editButton){if(index==0&&makeEditButtons.length>1){jQuery(editButton).parent().html("<span id='mjmh-override-button1'></span>");}});function gotoTile(mode,event){event.preventDefault();gotoInsideAsp("inside.asp?mode="+mode,null);}
jQuery("input#WPDEMCANCEL").on("click",function(event){gotoTile("patinfo",event);});jQuery("form#PrefsForm input#cancelform").on("click",function(event){gotoTile("patinfo",event);});jQuery("a[href*='inside.asp']").on("click",function(event){return clickedInsideAspLink(this,event);});function clickedInsideAspLink(insideAspLink,event){var hrefAttr=jQuery(insideAspLink).attr('href');var cssClass=jQuery(insideAspLink).attr('class');return gotoInsideAsp(hrefAttr,cssClass,event);}
function processInsideAspRequest(thisRequest){action=jQuery(thisRequest).attr("action");paramStartIndex=action.indexOf("?");if(jQuery('#mychartEpicFormChangeContextParameters').length==0){if(paramStartIndex>0){paramStartIndex++;parameters=action.substring(paramStartIndex);jQuery("<input id='mychartEpicFormChangeContextParameters' type='hidden' name='parameters' value='"+parameters+"' />").appendTo(thisRequest);}else{parameters=jQuery(thisRequest).serialize();jQuery("<input id='mychartEpicFormChangeContextParameters' type='hidden' name='parameters' value='"+parameters+"' />").appendTo(thisRequest);}}
if(jQuery('#originalMethod').length==0){jQuery("<input id='originalMethod' type='hidden' name='originalMethod' value='"+thisRequest.method+"' />").appendTo(thisRequest);}
if(thisRequest.method.toUpperCase()=='GET'){thisRequest.method="POST";}
if(jQuery('#inputSubjectRelId').length==0&&appContext.currentSubjectRelId){jQuery("<input type='hidden' id='inputSubjectRelId' name='subjectRelId' value='"+appContext.currentSubjectRelId+"' />").appendTo(thisRequest);}
if(jQuery('#inputRelatedSubjectId').length==0&&appContext.relatedSubjectId){jQuery("<input type='hidden' id='inputRelatedSubjectId' name='relatedSubjectId' value='"+appContext.relatedSubjectId+"' />").appendTo(thisRequest);}
if(jQuery('#inputRelatedSubjectIdType').length==0&&appContext.relatedSubjectIdType){jQuery("<input type='hidden' id='inputRelatedSubjectIdType' name='relatedSubjectIdType' value='"+appContext.relatedSubjectIdType+"' />").appendTo(thisRequest);}
if(jQuery('#inputRootMode').length==0){jQuery("<input type='hidden' name='rootMode' id='inputRootMode' value='"+appContext.rootMode+"' />").appendTo(thisRequest);}}
if(!(typeof appContext==='undefined')){jQuery("form#ccdform").append("<input id='rootMode' type='hidden' name='rootMode' value='"+appContext.rootMode+"' />");jQuery("form#ccdform").append("<input type='hidden' id='subjectRelId' name='subjectRelId' value='"+appContext.currentSubjectRelId+"' />");jQuery("form#ccdform").append("<input type='hidden' id='relatedSubjectId' name='relatedSubjectId' value='"+appContext.relatedSubjectId+"' />");jQuery("form#ccdform").append("<input type='hidden' id='relatedSubjectIdType' name='relatedSubjectIdType' value='"+appContext.relatedSubjectIdType+"' />");if(appContext.rootMode=="downloadsummary"){jQuery("div#datatile p").first().html("Your downloaded health summary contains a copy of your allergies, medications, current health issues, procedures, test results, and immunizations from MyJohnMuirHealth. You can store this record on portable devices or share with your healthcare providers.");jQuery("ul.sectiontabs li#li_open a img").first().attr('src','en-US/images/health_record.png')
jQuery("ul.sectiontabs li#li_open a span").first().html("Health Summary");jQuery("ul.sectiontabs li#li_protect a img").first().attr('src','en-US/images/accesslevel.png');jQuery("ul.sectiontabs li#li_protect a span").first().html("Health Summary");}
if(appContext.currentMode=="downloadsummary"&&(appContext.rootMode=="recentappts"||appContext.rootMode=="admissions"||appContext.rootMode=="downloadsummary")){var ccdButtonLnk=jQuery("form#ccdform div:nth-child(2) a#downloadccd").first();ccdButtonLnk.html(ccdButtonLnk.html().replace(/&nbsp;/g,""));jQuery("form#ccdform div:nth-child(2) a#downloadccd img").first().css("padding-right","10px");}}
jQuery("div#datatile a[onclick*='openWindow(\'inside.asp?mode=download&view=true']").each(function(index,elem){var rx=/openWindow\('(.*)'\)/g;var aOnClick=jQuery(elem).attr("onclick");var onClickValue=rx.exec(aOnClick);var previewUrl=onClickValue[1];jQuery(elem).removeAttr("onclick");createPostForm("previewForm");jQuery(elem).on("click",function(e){e.preventDefault();jQuery('#previewForm').attr('action',previewUrl);jQuery('#previewForm').submit(function(e){window.open('','previewWindow','resizable,status,scrollbars').focus();this.target='previewWindow';});jQuery("#previewForm").submit();});});function handleQuestionnairePrint(index,elem){jQuery(elem).attr("id","questionPrint_"+index);var onclickValue=jQuery(elem).attr("onclick");var rx=/window.open\(HTMLUnencode\('(.*)'\),/g;var openWindowUrl=rx.exec(onclickValue);var qtnPrintUrl=openWindowUrl[1];var printFormId="questionnairePrintForm_"+index;jQuery(elem).data("link",qtnPrintUrl);jQuery(elem).data("formId",printFormId);createPostForm(printFormId);jQuery(elem).on("click",function(e){e.preventDefault();var qtnPrintFormId=jQuery(this).data("formId");var qtnPrintAction=jQuery(this).data("link");jQuery('#'+qtnPrintFormId).attr('action',qtnPrintAction);var qpFromId=jQuery(this).attr("id");var winId="qpw_"+qpFromId;jQuery('#'+qtnPrintFormId).submit(function(e){window.open('',winId,'width=800,height=600,resizable,status,scrollbars').focus();this.target=winId;});jQuery('#'+qtnPrintFormId).submit();});jQuery(elem).removeAttr("onclick");jQuery(elem).removeAttr("href");jQuery(elem).removeAttr("target");jQuery(elem).attr("style","cursor:pointer;cursor:hand");}
jQuery(".scan").css("width","250px");jQuery("#imgScan").css("width","400px");jQuery("#imgScan").css("height","400px");});var myjmhAppName='myjmh-client';var tileAspAction="/"+myjmhAppName+"/tiles/inside.asp";var dashboardAction="/"+myjmhAppName+"/dashboard";function getPostAction(){var postAction=tileAspAction;if(appContext.currentMode==null||appContext.currentMode==''){postAction=dashboardAction;}
return postAction;}
function pickSubjectDashboard(relationshipId,relSubjectId,relSubjectIdType){pickPerson(relationshipId,relSubjectId,relSubjectIdType,dashboardAction);}
function pickSubject(relationshipId,relSubjectId,relSubjectIdType){pickPerson(relationshipId,relSubjectId,relSubjectIdType,getPostAction());}
function pickSelf(){pickPerson('','','',getPostAction());}
function pickPerson(relationshipId,relSubjectId,relSubjectIdType,landingPage){jQuery('#changeContext').attr('action',landingPage);jQuery('#changeContextParameters').attr('value',appContext.currentPageAction);jQuery('#changeContextSubjectRelId').attr('value',relationshipId);jQuery('#changeContextRelSubjectId').attr('value',relSubjectId);jQuery('#changeContextRelSubjectIdType').attr('value',relSubjectIdType);jQuery('#changeContextMode').attr('value',appContext.currentMode);jQuery('#changeContext').submit();}
function gotoInsideAsp(hrefAttr,cssClass,event){var url="";var parameters="";var mode="";var splitIndex=hrefAttr.indexOf('?');if(splitIndex>0){url=hrefAttr.substring(0,splitIndex);parameters=hrefAttr.substring(splitIndex+1);firstParamDelim=parameters.indexOf('&');if(firstParamDelim<0){tokens=parameters.split("=");if(tokens[0]=="mode"){mode=tokens[1];}}else{modeParam=parameters.substring(0,firstParamDelim);tokens=modeParam.split("=");if(tokens[0]=="mode"){mode=tokens[1];}}}else{url=dashboardAction;mode="";}
jQuery('#changeContext').attr('action',url);jQuery('#changeContextParameters').attr('value',parameters);jQuery('#changeContextSubjectRelId').attr('value',appContext.currentSubjectRelId);jQuery('#changeContextRelSubjectId').attr('value',appContext.relatedSubjectId);jQuery('#changeContextRelSubjectIdType').attr('value',appContext.relatedSubjectIdType);jQuery('#changeContextMode').attr('value',mode);if(cssClass&&cssClass.indexOf("anchorNode")!=-1){jQuery('#rootMode').attr('value',mode);}
if(cssClass&&cssClass.indexOf("button")!=-1&&mode.indexOf("appointments")!=-1){jQuery('#rootMode').attr('value',mode);}
jQuery('#changeContext').submit();return false;}
var assistTextMap={"You can download your summary or send it directly to another provider using the options below.":"Download/Send"};